name: List PR Changes and Call API

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get PR changes
        run: |
          # Debug info
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          
          # Define token to use (using PAT from secrets)
          TOKEN="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"
          
          # Get the diff using the GitHub REST API
          curl -s -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3.diff" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > diff.txt
          
          # List changed files using the GitHub REST API
          echo "Changed files:"
          curl -s -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" > files.json
          
          # Debug the response
          echo "API Response:"
          cat files.json
          
          # Try to extract filenames with a more robust approach
          if jq -e . files.json > /dev/null 2>&1; then
            if jq 'type' files.json | grep -q "array"; then
              jq -r '.[].filename' files.json
            else
              echo "Response is not an array"
              jq '.' files.json
            fi
          else
            echo "Invalid JSON response"
            cat files.json
          fi
      
      - name: Print diff
        run: |
          echo "=== DIFF OUTPUT ==="
          cat diff.txt
          echo "=== END DIFF ==="
          
      - name: AI PR Review
        run: |
          # Read the diff file
          DIFF_CONTENT=$(cat diff.txt)
          
          # Prepare the JSON payload
          JSON_PAYLOAD=$(jq -n \
            --arg pr_number "${{ github.event.pull_request.number }}" \
            --arg diff_string "$DIFF_CONTENT" \
            '{pr_number: $pr_number, diff_string: $diff_string}')
          
          # Call the AI PR review API
          echo "Calling AI PR Review API..."
          curl --location 'https://pr-review-agent-demo-442640027315.us-central1.run.app' \
            --header 'Content-Type: application/json' \
            --data "$JSON_PAYLOAD"
          
          echo "AI PR Review completed" 