name: List PR Changes and Call API

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get PR changes
        run: |
          # Debug info
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          
          # Define token to use (using PAT from secrets)
          TOKEN="${{ secrets.PR_ACCESS_TOKEN }}"
          
          # Get the diff using the GitHub REST API
          curl -s -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3.diff" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > diff.txt
          
          # List changed files using the GitHub REST API
          echo "Changed files:"
          curl -s -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | \
            jq -r '.[].filename'
      
      - name: Print diff
        run: |
          echo "=== DIFF OUTPUT ==="
          cat diff.txt
          echo "=== END DIFF ==="
