name: PR Review with AI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      
      - name: Call AI Review API
        run: |
          # Read the diff file

          
          # Prepare the JSON payload with hardcoded token
          JSON_PAYLOAD=$(jq -n \
            --arg pr_number "${{ github.event.pull_request.number }}" \
            --arg diff_string "$DIFF_CONTENT" \
            --arg repo "${{ github.repository }}" \
            '{
              pr_number: $pr_number,
              repo: $repo,
              token: "test-token"
            }')
          
          # Call the AI PR review API
          echo "Calling AI PR Review API..."
          RESPONSE=$(curl --location 'https://pr-review-agent-demo-442640027315.us-central1.run.app/reviews' \
            --header 'Content-Type: application/json' \
            --data "$JSON_PAYLOAD")
          
          echo "API Response: $RESPONSE"
          
          # Check if the API call was successful
          if [[ "$RESPONSE" == *"success"* ]]; then
            echo "AI PR Review completed successfully"
          else
            echo "AI PR Review failed"
            echo "$RESPONSE"
            exit 1
          fi 