name: PR Review with AI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get PR diff
        id: get-diff
        run: |
          # Get the PR diff directly from GitHub
          curl -s -o pr_diff.txt \
            "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}.diff"
          
          # Check if we got the diff
          if [ -s pr_diff.txt ]; then
            echo "Successfully retrieved PR diff"
          else
            echo "Failed to retrieve PR diff"
            exit 1
          fi
          
          # Print some stats about the diff
          echo "Diff size: $(wc -c < pr_diff.txt) bytes"
          echo "Changed files: $(grep -c "^diff --git" pr_diff.txt)"
      
      - name: Call AI Review API
        run: |
          # Read the diff file
          DIFF_CONTENT=$(cat pr_diff.txt)
          
          # Prepare the JSON payload - escape special characters
          JSON_PAYLOAD=$(jq -n \
            --arg pr_number "${{ github.event.pull_request.number }}" \
            --arg diff_string "$DIFF_CONTENT" \
            '{pr_number: $pr_number, diff_string: $diff_string}')
          
          # Call the AI PR review API
          echo "Calling AI PR Review API..."
          RESPONSE=$(curl --location 'https://pr-review-agent-demo-442640027315.us-central1.run.app/reviews' \
            --header 'Content-Type: application/json' \
            --data "$JSON_PAYLOAD")
          
          echo "API Response: $RESPONSE"
          
          # Check if the API call was successful
          if [[ "$RESPONSE" == *"success"* ]]; then
            echo "AI PR Review completed successfully"
          else
            echo "AI PR Review failed"
            echo "$RESPONSE"
            exit 1
          fi 