name: PR Diff and AI Review Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-diff-and-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get diff
        id: git-diff-action
        uses: GrantBirki/git-diff-action@v1.0.0
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"

      - name: Get diff and review
        run: |
          diff=$(cat diff.txt || echo 'No diff available')
          echo "Git diff:"
          echo "$diff"
          curl -X POST \
            https://your-ai-agent.com/api/review \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.AI_AGENT_TOKEN }}' \
            -d '{"repository": "${GITHUB_REPOSITORY}", "pullRequestNumber": "${GITHUB_EVENT_NUMBER}", "diff": "'"$diff"'"}'
