name: List PR Changes and Call API

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Fetch all branches
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          
      - name: List changes
        run: |
          # Get the PR base and head refs
          echo "Base branch: ${GITHUB_BASE_REF}"
          echo "Head branch: ${GITHUB_HEAD_REF}"
          echo "PR number: ${{ github.event.number }}"
          
          # Get the diff directly using GitHub's PR comparison
          DIFF=$(git diff origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF})
          
          # Save diff to a file
          echo "$DIFF" > diff.txt
          
          # Print a summary of changed files
          echo "Changed files:"
          git diff --name-only origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}
      
      - name: Print diff
        run: |
          echo "=== DIFF OUTPUT ==="
          cat diff.txt
          echo "=== END DIFF ==="
